import '@std/dotenv/load'
const { ID_GITHUB, SECRET_GITHUB, DESEC_TOKEN, DEV, DOMAIN, MAINPAGE, BANNED_DOMAINS, GITHUB_API, GITHUB_AUTHORIZATION_DOMAIN } = Deno.env.toObject()
const DOMAIN_LIMIT = 6
export { DESEC_TOKEN, DEV, ID_GITHUB, SECRET_GITHUB, DOMAIN, MAINPAGE, BANNED_DOMAINS, GITHUB_API, GITHUB_AUTHORIZATION_DOMAIN, DOMAIN_LIMIT }